In [24]:
import pandas as pd
import numpy as np

data_set= pd.read_csv('creditcard.csv')
data_set

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [25]:
# confirming that the outcomes are binary 1= fraudulent 0=non-fradualent
data_set['Class'].unique()

array([0, 1], dtype=int64)

In [26]:
# extracting numerical values from data 
features= data_set.columns.drop(['Class'])
X=data_set[features].values
Y=data_set['Class'].values
X

array([[ 0.00000000e+00, -1.35980713e+00, -7.27811733e-02, ...,
         1.33558377e-01, -2.10530535e-02,  1.49620000e+02],
       [ 0.00000000e+00,  1.19185711e+00,  2.66150712e-01, ...,
        -8.98309914e-03,  1.47241692e-02,  2.69000000e+00],
       [ 1.00000000e+00, -1.35835406e+00, -1.34016307e+00, ...,
        -5.53527940e-02, -5.97518406e-02,  3.78660000e+02],
       ...,
       [ 1.72788000e+05,  1.91956501e+00, -3.01253846e-01, ...,
         4.45477214e-03, -2.65608286e-02,  6.78800000e+01],
       [ 1.72788000e+05, -2.40440050e-01,  5.30482513e-01, ...,
         1.08820735e-01,  1.04532821e-01,  1.00000000e+01],
       [ 1.72792000e+05, -5.33412522e-01, -1.89733337e-01, ...,
        -2.41530880e-03,  1.36489143e-02,  2.17000000e+02]])

In [27]:
# Splitting the data into the test data and training data
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(X,Y,test_size=0.2,random_state=0)
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
# data preprocessing by standardizing the data features
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[-0.87750986, -0.57177938,  0.62828369, ...,  0.57377804,
        -0.2196612 , -0.30511629],
       [-1.15308534,  0.62679248, -0.08362249, ..., -0.17091545,
         0.00631402, -0.25423683],
       [ 1.26383162,  0.98361214, -0.1198731 , ...,  0.13283995,
        -0.10128286, -0.32950779],
       ...,
       [-0.38349503,  0.77210803, -0.57499928, ..., -0.00209668,
         0.01184758, -0.21662151],
       [ 0.05096267,  0.91851362, -1.02985151, ..., -0.08231776,
        -0.10081197,  0.33333622],
       [-0.41989457, -0.30294167,  0.45385207, ...,  0.21715744,
         0.36857129, -0.29286006]])

# Ensemble Methods

## Random Forest Classifier

In [29]:
# training the features with random forest model
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(n_estimators=100, max_depth=5, random_state=0)
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [30]:
y_prediction=rf.predict(x_test)
y_prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [31]:
from sklearn import metrics

rand_forest_accuracy=metrics.accuracy_score(y_test,y_prediction)*100

## Logistic Regression

In [32]:
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
y_prediction=lr.predict(x_test)
y_prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [34]:
log_reg_accuracy=metrics.accuracy_score(y_test,y_prediction)*100

## Naive Bayes

In [35]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)


GaussianNB(priors=None, var_smoothing=1e-09)

In [36]:
y_prediction=nb.predict(x_test)
y_prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [37]:
naive_bayes=metrics.accuracy_score(y_test,y_prediction)*100

## Decision Tree

In [38]:
from sklearn.tree import DecisionTreeClassifier

dt= DecisionTreeClassifier(criterion='entropy', random_state=0)
dt.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [39]:
y_prediction=dt.predict(x_test)
y_prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [40]:
Dec_tree=metrics.accuracy_score(y_test,y_prediction)*100

## XGBoost

In [41]:
from xgboost import XGBClassifier
xgb= XGBClassifier()
xgb.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [42]:
y_prediction= xgb.predict(x_test)
y_prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [43]:
xgboost=metrics.accuracy_score(y_test,y_prediction)*100

## Artificial Neural Network

In [46]:
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.models import Sequential

ann=Sequential()
# input layer
ann.add(Dense(56,activation='relu'))
ann.add(Dropout(0.2))
# hidden layer
ann.add(Dense(56,activation='relu'))
ann.add(Dropout(0.2))

ann.add(Dense(56,activation='relu'))
ann.add(Dropout(0.2))

ann.add(Dense(56,activation='relu'))
ann.add(Dropout(0.2))
# output layer
ann.add(Dense(1,activation='sigmoid'))

# compiling the ann
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
# training the ann
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
227845/227845 [==============================] - 138s 605us/sample - loss: 0.0080 - acc: 0.9987
Epoch 2/100
227845/227845 [==============================] - 107s 469us/sample - loss: 0.0045 - acc: 0.9993- loss: 0.
Epoch 3/100
227845/227845 [==============================] - 131s 575us/sample - loss: 0.0042 - acc: 0.9993
Epoch 4/100
227845/227845 [==============================] - 121s 533us/sample - loss: 0.0041 - acc: 0.9993
Epoch 5/100
227845/227845 [==============================] - 117s 514us/sample - loss: 0.0040 - acc: 0.9994
Epoch 6/100
227845/227845 [==============================] - 129s 564us/sample - loss: 0.0033 - acc: 0.9993- loss: 0.0033 - acc: 0.9
Epoch 7/100
227845/227845 [==============================] - 116s 511us/sample - loss: 0.0037 - acc: 0.9994- loss: - ETA: 2s - loss: 0.0037 - acc: 0.
Epoch 8/100
227845/227845 [==============================] - 140s 613us/s

227845/227845 [==============================] - 91s 400us/sample - loss: 0.0032 - acc: 0.9995
Epoch 67/100
227845/227845 [==============================] - 130s 571us/sample - loss: 0.0031 - acc: 0.9995 3s -
Epoch 68/100
227845/227845 [==============================] - 161s 705us/sample - loss: 0.0046 - acc: 0.9995-
Epoch 69/100
227845/227845 [==============================] - 216s 948us/sample - loss: 0.0036 - acc: 0.9995
Epoch 70/100
227845/227845 [==============================] - 173s 761us/sample - loss: 0.0026 - acc: 0.9995- los
Epoch 73/100
227845/227845 [==============================] - 104s 458us/sample - loss: 0.0036 - acc: 0.9995
Epoch 74/100
227845/227845 [==============================] - 107s 470us/sample - loss: 0.0025 - acc: 0.9995- loss: 0.0026 - acc: 0.999 - ETA: 1s - l
Epoch 75/100
227845/227845 [==============================] - ETA: 0s - loss: 0.0041 - acc: 0.9995- ETA: 1s  - 100s 438us/sample - loss: 0.0041 - acc: 0.9995
Epoch 76/100
227845/227845 [=============

In [48]:
y_prediction=ann.predict(x_test)
y_prediction

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [53]:
ann_accuracy=ann.evaluate(x_test,y_test)
ann_accuracy[1]

56962/56962 [==============================] - 17s 296us/sample - loss: 0.0598 - acc: 0.9995 - 


0.99947333

In [54]:
# A dictionary list of differerent model prediction accuracies
model_accuracy_dict={"Random Forest Classifier": rand_forest_accuracy,
                     "Logistic Regression": log_reg_accuracy,
                     "Naive Bayes Classifier": naive_bayes, 
                     "Decision Tree Classifier": Dec_tree, 
                     "XGBoost Classifier": xgboost,
                     "ANN": ann_accuracy[1]*100}
            
model_accuracy_dict

{'Random Forest Classifier': 99.93504441557529,
 'Logistic Regression': 99.91924440855307,
 'Naive Bayes Classifier': 97.82311014360451,
 'Decision Tree Classifier': 99.91573329588147,
 'XGBoost Classifier': 99.95962220427653,
 'ANN': 99.94733333587646}

In [55]:
# display optimum prediction accuracy percentage
print('optimum prediction accuracy percentage:',max(model_dict.values()))

optimum prediction accuracy percentage: 99.95962220427653
